version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    image: hanami-ruby:latest
    platform: linux/amd64
    volumes:
      - .:/app
    command: "bundle exec iodine -v"
    env_file: ".env.dev"
    ports:
      - 3000:3000
    depends_on:
      - assets
    links:
      - assets
  assets:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: hanami-node:latest
    platform: linux/amd64
    env_file: ".env.dev"
    volumes:
      - ./slices:/app/slices
    ports:
      - "8080:8080"
    command: "npm run start"
