version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ruby
      # tag: hanami-ephemeral-chat
    image: hanami-ruby:latest
    platform: linux/amd64
    volumes:
      - .:/app
      - vendor:/app/vendor
    command: ["script/puma"]
    env_file: ".env"
    ports:
      - 2300:2300
    # depends_on:
    #   - assets
    # links:
    #   - assets
  assets:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: hanami-node:latest
    platform: linux/amd64
    env_file: ".env"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    expose:
      - "8080"
    command: "npm start"
volumes:
  vendor:
  node_modules:
